[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

solc_version = "0.8.4"
optimizer = true
optimizer_runs = 777
gas_limit = "18446744073709551615"


[rpc_endpoints]
base = "https://api.developer.coinbase.com/rpc/v1/base/0t7BcTpi0c8484WTg3oA39OHVeTiMa1u"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base = { key = "7MGFD34AITGUD7GWJRNACV37SVJYKFFRPT" }
base_sepolia = { key = "7MGFD34AITGUD7GWJRNACV37SVJYKFFRPT" }

